version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.1

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  run-todo-app-job:
    type: boolean
    default: false

# here we specify our workflows, most of which are conditionally
# executed based upon pipeline parameter values. Each workflow calls a
# specific job defined above, in the jobs section.

# jobs are omited for this purpose
workflows:
  # when pipeline parameter, run-design-system-job is true, the
  # jobs is triggered.
  todo-app:
    when: << pipeline.parameters.run-todo-app-job >>
    jobs:
      - tests
      - lighthouse-mobile
      - build

jobs:
  lighthouse-mobile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/install-packages:
          pkg-manager: npm
      - run: node --version
      - run: npm install @lhci/cli
      - run: npm build && lhci autorun --config=./lighthouse-mobile.js
      - store_artifacts:
          path: /tmp/lighthouseci
          destination: lighthouse-mobile-report
  tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: node --version
      - run: nx test
      - run: nx build
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: node --version
      - run: nx build
