version: 2.1

orbs:
  nx: nrwl/nx@1.6.1
  browser-tools: circleci/browser-tools@1.4.1

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  run-todo-app-job:
    type: boolean
    default: true

# here we specify our workflows, most of which are conditionally
# executed based upon pipeline parameter values. Each workflow calls a
# specific job defined above, in the jobs section.

# jobs are omited for this purpose
workflows:
  # when pipeline parameter, run-design-system-job is true, the
  # jobs is triggered.
  todo-app:
    when: << pipeline.parameters.run-todo-app-job >>
    jobs:
      - tests
      - lighthouse-mobile:
          requires:
            - tests
            - build
      - build:
          requires:
            - tests

jobs:
  tests:
    working_directory: ~/front-end-mentor
    docker:
      - image: cimg/node:18.15.0-browsers
    environment:
      MAIN_BRANCH_NAME: master
    steps:
      - checkout:
          path: ~/front-end-mentor
      - run: cd todo-app/ && yarn install --froze-lockfile
      - nx/set-shas:
          allow-on-hold-workflow: true
          error-on-no-successful-workflow: true
          main-branch-name: master
          workflow-name: nx-pipeline
      - run: cd todo-app/ && yarn nx affected --target=test --base=$NX_BASE
  lighthouse-mobile:
    working_directory: ~/front-end-mentor
    docker:
      - image: cimg/node:18.15.0-browsers
    environment:
      MAIN_BRANCH_NAME: master
    steps:
      - checkout:
          path: ~/front-end-mentor
      - run: cd todo-app/ && yarn install --froze-lockfile
      - nx/set-shas:
          allow-on-hold-workflow: true
          error-on-no-successful-workflow: true
          main-branch-name: master
          workflow-name: nx-pipeline
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: cd todo-app/ && node --version
      - run: cd todo-app/ && yarn global add @lhci/cli
      - run: cd todo-app/ && yarn nx affected --target=build --base=$NX_BASE 
      - run: lhci autorun --collect.staticDistDir='./todo-app/dist' --config=./lighthouse-mobile.js
      - store_artifacts:
          path: /tmp/lighthouseci
          destination: lighthouse-mobile-report
  build:
    working_directory: ~/front-end-mentor
    docker:
      - image: cimg/node:18.15.0-browsers
    steps:
      - checkout:
          path: ~/front-end-mentor
      - run: cd todo-app/ && yarn install --froze-lockfile
      - nx/set-shas:
          allow-on-hold-workflow: true
          error-on-no-successful-workflow: true
          main-branch-name: master
          workflow-name: nx-pipeline
      - run: cd todo-app/ &&  node --version
      - run: cd todo-app/ && yarn nx affected --target=build --base=$NX_BASE
