version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.1

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  run-todo-app-job:
    type: boolean
    default: true

# here we specify our workflows, most of which are conditionally
# executed based upon pipeline parameter values. Each workflow calls a
# specific job defined above, in the jobs section.

# jobs are omited for this purpose
workflows:
  # when pipeline parameter, run-design-system-job is true, the
  # jobs is triggered.
  todo-app:
    when: << pipeline.parameters.run-todo-app-job >>
    jobs:
      - tests
      - lighthouse-mobile
      # - build

jobs:
  tests:
    working_directory: ~/front-end-mentor
    executor: node/default
    docker:
      - image: cimg/base:stable
    steps:
      - checkout:
          path: ~/front-end-mentor
      - node/install
      - node/install-packages:
          app-dir: todo-app/
          override-ci-command: npm install
      - run: cd todo-app/ && npm run test
  lighthouse-mobile:
    working_directory: ~/front-end-mentor
    executor: node/default
    docker:
      - image: cimg/base:stable
    steps:
      - checkout:
          path: ~/front-end-mentor
      - node/install
      - node/install-packages:
        app-dir: todo-app/
        override-ci-command: npm install
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: cd todo-app/ && node --version
      - run: cd todo-app/ && npm install @lhci/cli
      - run: cd todo-app/ && npm build && lhci autorun --config=./lighthouse-mobile.js
      - store_artifacts:
          path: /tmp/lighthouseci
          destination: lighthouse-mobile-report
  # build:
  #   working_directory: ~/front-end-mentor
  #   executor: node/default
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     - checkout:
  #         path: ~/front-end-mentor
  #     - run: sudo npm install -g npm@latest
  #     - node/install-packages:
  #         app-dir: todo-app/
  #     - run: cd todo-app/ &&  node --version
  #     - run: cd todo-app/ && nx build
