version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.1

workflows:
  main:
    jobs:
      - tests

jobs:
  tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          node-version: '18.15'
      - run: node --version
      - run: nx test
      - run: nx build